#!/usr/bin/env node
/**
 * Pre-build config injection for the Airlancer IDE extension.
 *
 * Reads AIRLANCER_ENV (default: "dev") and generates src/generated/config.ts
 * with environment-specific default URLs. This runs before tsc so the
 * constants are baked into the compiled .vsix.
 *
 * Usage:
 *   AIRLANCER_ENV=dev  node scripts/inject-config.js   # development
 *   AIRLANCER_ENV=prod node scripts/inject-config.js   # production
 */
const fs = require('fs');
const path = require('path');

const env = process.env.AIRLANCER_ENV || 'dev';

const configs = {
  dev: {
    mcpServerUrl: 'https://mcp-dev.airlancer.ai',
    dashboardUrl: 'https://adlc-dev.airlancer.ai',
    apiBaseUrl: 'https://api-dev.airlancer.ai',
  },
  prod: {
    mcpServerUrl: 'https://mcp.airlancer.ai',
    dashboardUrl: 'https://adlc.airlancer.ai',
    apiBaseUrl: 'https://api.airlancer.ai',
  },
};

const cfg = configs[env];
if (!cfg) {
  console.error(`[inject-config] Unknown AIRLANCER_ENV: "${env}". Use "dev" or "prod".`);
  process.exit(1);
}

const output = `// AUTO-GENERATED by scripts/inject-config.js — do not edit manually.
// Environment: ${env}
// Generated: ${new Date().toISOString()}

/** Default MCP server URL for this build */
export const DEFAULT_MCP_SERVER_URL = '${cfg.mcpServerUrl}';

/** Default dashboard URL for browser links */
export const DEFAULT_DASHBOARD_URL = '${cfg.dashboardUrl}';

/** Default API base URL */
export const DEFAULT_API_BASE_URL = '${cfg.apiBaseUrl}';

/** Build environment identifier */
export const BUILD_ENV = '${env}' as const;
`;

const outDir = path.join(__dirname, '..', 'src', 'generated');
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'config.ts'), output);
console.log(`[inject-config] Generated src/generated/config.ts for env=${env}`);
